# Generated by Django 4.0.4 on 2022-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visit',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
